# src/main/resources/application.yml
server:
  port: 8080
  servlet:
    context-path: /payment-system

spring:
  application:
    name: payment-bridge-system
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.payment: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"